### ISSUE TITLE
Crash related to Android toasts

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#1305]
### Steps to reproduce
On a device running Android 8 or 9, either:
- Trigger actions which cause quick changes of the Android toast messages, or
- insert a `toast.cancel()` before `toast.show()` in `onTick()` of MapperActivity.java.

### Actual behaviour
The app sooner or later crashes:
~~~
D Surface : Surface::disconnect(this=0x90499000,api=1)
D GraphicBuffer: unregister, handle(0x8f764a40) (w:52 h:87 s:64 f:0x1 u:f02)
D View    : [Warning] assignParent to null: this = android.widget.LinearLayout{b29ac2e V.E...... ......ID 0,0-87,52}
D WindowClient: Remove from mViews: android.widget.LinearLayout{b29ac2e V.E...... ......ID 0,0-87,52}, this = android.view.WindowManagerGlobal@4ec0af7
D WindowClient: Add to mViews: android.widget.LinearLayout{b29ac2e V.E...... ......ID 0,0-87,52}, this = android.view.WindowManagerGlobal@4ec0af7
D ViewRootImpl[Toast]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.openorienteering.mapper.dev, PID: 8060
E AndroidRuntime: java.lang.IllegalStateException: View android.widget.LinearLayout{b29ac2e V.E...... ......ID 0,0-87,52} has already been added to the window manager.
E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:328)
E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:496)
E AndroidRuntime: 	at android.widget.Toast$TN$1.handleMessage(Toast.java:400)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
~~~

### Expected behaviour
No crash. 

### Configuration
Mapper Version: `dev` (2019-08-01)
Operating System: Android 8, 9

**Comment by dg0yt** [comment]
First mentioned in discussion of #1296. Related discussion:
- https://stackoverflow.com/questions/51956971/illegalstateexception-of-toast-view-on-android-p-preview
- https://stackoverflow.com/questions/54624116/android-java-lang-illegalstateexception-in-toast-handleshow
- https://issuetracker.google.com/issues/71731536
- https://android-review.googlesource.com/c/platform/frameworks/base/+/583926

Note there seems to be an attempt to remove the view from the window manager before failing for the view already being added to the window manager ... and the unmerged gerrit submission adding another, *immediate* removal in this particular case.

**Comment by dg0yt** [comment]
Our usage of Toast is atypical in the following ways:
- we reuse the same toast, 
- we try to control the duration the toast is displayed.

I would suggest to replace the native Toast by a Qt C++ solution which can be used on desktops, too.
