### ISSUE TITLE
Mapper crashes when rotating large template

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#2143]
### Steps to reproduce
1. Open the attached map
2. Select in template window Edit->Positioning
3. Enter a value in the 'Rotation' field

### Actual behaviour
Mapper crashes.

### Expected behaviour
Mapper should at least issue a warning that the rotation of the template cannot be performed (even if the size of the template
does not represent a realistic usecase).

### Configuration
Mapper Version: 0.95/Current Master (Debug)
Operating System: Win7/Ubuntu
[LargeTemplateCrash.zip](https://github.com/OpenOrienteering/mapper/files/11066083/LargeTemplateCrash.zip)

**Comment by lpechacek** [comment]
Confirmed. The process crashes deep in Qt code which suggests inconsistent `QImage` data rather than a straightforward programmatic error. I'm attaching a partial backtrace for illustration. The bug is easy to replicate.

```
#0  fetchTransformedBilinearARGB32PM_fast_rotate_helper_avx2(unsigned int*, unsigned int*, QTextureData const&, int&, int&, int, int)
    (b=0x7fffffff9cb0, end=0x7fffffffab38, image=..., fx=@0x7fffffff7b30: 526803398, fy=@0x7fffffff7b34: 458696704, fdx=654798, fdy=11429)
    at painting/qdrawhelper_avx2.cpp:941
#1  0x00007ffff7401294 in fetchTransformedBilinearARGB32PM<(TextureBlendType)4>(uint*, Operator const*, QSpanData const*, int, int, int)
    (buffer=0x7fffffff9cb0, data=<optimized out>, y=<optimized out>, x=<optimized out>, length=930) at painting/qdrawhelper.cpp:3107
#2  0x00007ffff741b32f in BlendSrcGeneric::fetch(int, int, int) (len=<optimized out>, y=0, x=0, this=0x7fffffff7c10)
    at painting/qdrawhelper.cpp:4764
#3  handleSpans<BlendSrcGeneric>(int, QT_FT_Span_ const*, QSpanData const*, BlendSrcGeneric&)
    (count=256, spans=0x7fffffffbeb0, data=<optimized out>, handler=...) at painting/qdrawhelper.cpp:4708
#4  0x00007ffff7418dbd in blend_src_generic(int, QSpan const*, void*) (count=<optimized out>, spans=<optimized out>, userData=<optimized out>)
    at painting/qdrawhelper.cpp:4816
#5  0x00007ffff74abcc3 in QSpanBuffer::flushSpans() (this=0x7fffffffbeb0) at painting/qrasterizer.cpp:113
#6  QSpanBuffer::addSpan(int, unsigned int, int, unsigned char)
    (x=<optimized out>, len=<optimized out>, y=255, coverage=255 '\377', this=0x7fffffffbeb0) at painting/qrasterizer.cpp:107
#7  QSpanBuffer::addSpan(int, unsigned int, int, unsigned char)
    (coverage=255 '\377', y=255, len=<optimized out>, x=<optimized out>, this=0x7fffffffbeb0) at painting/qrasterizer.cpp:91
#8  QRasterizer::rasterizeLine(QPointF const&, QPointF const&, double, bool) (this=<optimized out>, a=..., b=..., width=<optimized out>, 
    width@entry=0.52554545454545454, squareCap=squareCap@entry=false) at painting/qrasterizer.cpp:1185
#9  0x00007ffff74549b9 in QRasterPaintEngine::drawImage(QRectF const&, QImage const&, QRectF const&, QFlags<Qt::ImageConversionFlag>)
    (this=<optimized out>, r=<optimized out>, img=<optimized out>, sr=...) at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:116
#10 0x00007ffff745619c in QRasterPaintEngine::drawImage(QRectF const&, QImage const&, QRectF const&, QFlags<Qt::ImageConversionFlag>)
    (sr=..., img=..., r=..., this=0x3078ad0) at ../../include/QtCore/../../src/corelib/tools/qrect.h:674
#11 QRasterPaintEngine::drawImage(QPointF const&, QImage const&) (this=0x3078ad0, p=..., img=...) at painting/qpaintengine_raster.cpp:2189
#12 0x000000000100352e in OpenOrienteering::TemplateImage::drawTemplate(QPainter*, QRectF const&, double, bool, double) const
    (this=0x2cf22b0, painter=0x7fffffffcb88, opacity=1) at /data/src/oomapper/src/templates/template_image.cpp:363
#13 0x0000000000587fed in OpenOrienteering::Map::drawTemplates(QPainter*, QRectF const&, int, int, OpenOrienteering::MapView const*, bool) const
    (this=0x2bda510, painter=0x7fffffffcb88, bounding_box=..., first_template=0, last_template=0, view=0x2cdebe0, on_screen=true)
    at /data/src/oomapper/src/core/map.cpp:876
#14 0x0000000000c78a67 in OpenOrienteering::MapWidget::updateTemplateCache(QImage&, QRect&, int, int, bool)
    (this=0x2cf2550, cache=..., dirty_rect=..., first_template=0, last_template=0, use_background=true)
    at /data/src/oomapper/src/gui/map/map_widget.cpp:1343
#15 0x0000000000c7b911 in OpenOrienteering::MapWidget::updateAllDirtyCaches() (this=0x2cf2550)
    at /data/src/oomapper/src/gui/map/map_widget.cpp:1418
#16 0x0000000000c6212e in OpenOrienteering::MapWidget::paintEvent(QPaintEvent*) (this=0x2cf2550, event=0x7fffffffd010)
    at /data/src/oomapper/src/gui/map/map_widget.cpp:870
```

**Comment by dl3sdo** [comment]
@lpechacek: thank you for the analysis. My first impression was also that this might be an issue of QT.
I found this known (and already solved issue):
[QTransform rotate big image will crash](https://bugreports.qt.io/browse/QTBUG-99163)
